# -*- coding: utf-8 -*-
"""APIkey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIWUu3MMGSPffpXCmUGbWslNUW1Msnqu

**Install the OpenAI Python Client**

**create a secret key in OpenAI dashboard->APIKey**
"""

!pip show openai

!pip uninstall openai
#!pip install openai

!pip install openai==0.28.0

import openai
import os

# Set your API key directly using os.environ
# Normally, you should set this environment variable outside of your script for security reasons.
os.environ["OPENAI_API_KEY"] = ''	# update with your own OpenAI GPT API keys


# Ensure your API key is set from the environment variable
openai.api_key = os.getenv("OPENAI_API_KEY")

# Check if the API key is properly loaded
if openai.api_key is None:
    raise ValueError("API key not found. Please set the OPENAI_API_KEY environment variable.")

try:
    # Example request using the OpenAI API
    response = openai.ChatCompletion.create(
        model="gpt-4o-mini",  # Specify the model to be used, e.g., "gpt-4" or "gpt-3.5-turbo"
        messages=[
            {"role": "system", "content": "I am An AI agent in Equity research"},
            {"role": "user", "content": "Provide Tesla earning report as of 2019"}
        ],
        max_tokens=60
    )

    # Output the response
    print(response['choices'][0]['message']['content'].strip())

except openai.error.OpenAIError as e:
    # Handle OpenAI API error
    print(f"OpenAI API error: {e}")

except Exception as e:
    # Handle other exceptions
    print(f"An error occurred: {e}")

"""EarningTweet AI is the earning conference call transcript intelligent aggregator. Following sample posts in the knowledge, It explain the earning call summary into 8 sections:
S1: Financial and operational highlights:
Revenue by sectors, gross margins by sectors, growth rate
Cash reserve, R&D and marketing expense
Delivery and growth rate
S2: Market Expansion
S3: strategic cooperation
S4: New Product Launch
S5: Management change
S6: Management comments
S7: Next quarter forward estimates
S8: List out all Analysts' Q&A
Executive management team comments and Analyst Q&A are the most important contents in the summary.
then present the summary in bullet points provide a concise summary of each section
Based on the most recent quarter earning call transcript, combined with the last 4 quarters financials updates, answer questions from conversation starters.
After explain the earning call, prompt to ask if willing to retrieve full earning transcript.
"""