# -*- coding: utf-8 -*-
"""Connect2Social

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hd0HK8N_s7DAQcYVk6eJKfchnsdN-T0K

**connect to social media or investor's forum to get questions from investors**
"""

!pip install requests beautifulsoup4 lxml

!pip install selenium

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time

# Configure Chrome options for headless mode
chrome_options = Options()
chrome_options.add_argument("--headless")  # Run in headless mode
chrome_options.add_argument("--no-sandbox")  # Bypass OS security model
chrome_options.add_argument("--disable-dev-shm-usage")  # Overcome limited resource problems
chrome_options.add_argument("--disable-gpu")  # Applicable to Windows OS only
chrome_options.add_argument("--remote-debugging-port=9222")  # Use a different port to avoid conflicts

# Initialize the WebDriver with options
driver = webdriver.Chrome(options=chrome_options)

try:
    # Open a webpage
    driver.get("https://app.saytechnologies.com/tesla-2024-q2")

    # Wait for the content to load
    time.sleep(5)  # Adjust this based on network speed

    # Find elements containing questions
    # Update the selector based on the actual HTML structure
    questions = driver.find_elements(By.CLASS_NAME, "Question")

    # Extract and print the top 10 questions
    for i, question in enumerate(questions[:10], start=1):
        print(f"Question {i}: {question.text}")

finally:
    # Close the browser
    driver.quit()

!pip install webdriver-manager

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
import time

# Configure Chrome options for headless mode
chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--remote-debugging-port=9222")

# Automatically manage WebDriver with WebDriverManager
chrome_options.binary_location = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

try:
    # Open a webpage
    driver.get("https://app.saytechnologies.com/tesla-2024-q2")

    # Wait for the content to load
    time.sleep(5)  # Adjust this based on network speed

    # Find elements containing questions
    # Update the selector based on the actual HTML structure
    questions = driver.find_elements(By.CLASS_NAME, "Question")

    # Extract and print the top 10 questions
    for i, question in enumerate(questions[:10], start=1):
        print(f"Question {i}: {question.text}")

finally:
    # Close the browser
    driver.quit()